from sqlalchemy import Integer, String, ForeignKey, Float, Boolean, DateTime, Text
from sqlalchemy.orm import relationship, Mapped, mapped_column
from pgvector.sqlalchemy import Vector
from app.core.database import Base
from datetime import datetime
from typing import List, Optional

class Store(Base):
    __tablename__ = "stores"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    umkm_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("users.id"), nullable=True)
    name: Mapped[str] = mapped_column(String, index=True, nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=False)
    enhanced_description: Mapped[str | None] = mapped_column(String, nullable=True)
    province: Mapped[str] = mapped_column(String, nullable=False)
    city: Mapped[str] = mapped_column(String, nullable=False)
    address: Mapped[str] = mapped_column(String, nullable=False)
    latitude: Mapped[float | None] = mapped_column(Float, nullable=True) # next shoud be generated by maps
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True) # next shoud be generated by maps
    image_url: Mapped[str | None] = mapped_column(String, nullable=True)
    suggestion: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggestion_complete: Mapped[bool | None] = mapped_column(Boolean, default=False)
    embedding: Mapped[Vector] = mapped_column(Vector(1536), nullable=False) # OpenAI embedding dimension
    is_valid_store: Mapped[bool | None] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime | None] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    umkm: Mapped["User"] = relationship("User", back_populates="umkm_stores") 
    foods: Mapped[List["Food"]] = relationship("Food", back_populates="store")
    reviews: Mapped[List["Review"]] = relationship("Review", back_populates="store")
