from sqlalchemy import Column, Integer, String, ForeignKey, Float, Boolean, DateTime, Text
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from app.core.database import Base
from datetime import datetime

class Store(Base):
    __tablename__ = "stores"

    id = Column(Integer, primary_key=True, index=True)
    umkm_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    name = Column(String, index=True, nullable=False)
    description = Column(String, nullable=False)
    enhanced_description = Column(String, nullable=True)
    province = Column(String, nullable=False)
    city = Column(String, nullable=False)
    address = Column(String, nullable=False)
    latitude = Column(Float, nullable=True) # next shoud be generated by maps
    longitude = Column(Float, nullable=True) # next shoud be generated by maps
    image_url = Column(String, nullable=True)
    suggestion = Column(Text, nullable=True)
    suggestion_complete = Column(Boolean, default=False)
    embedding = Column(Vector(1536), nullable=False) # OpenAI embedding dimension
    is_valid_store = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    umkm = relationship("User", back_populates="umkm_stores") 
    foods = relationship("Food", back_populates="store")
    reviews = relationship("Review", back_populates="store")
