"""change user role to enum

Revision ID: 3ae053fca305
Revises: 10c7115345f7
Create Date: 2025-12-06 13:08:11.030144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3ae053fca305'
down_revision: Union[str, Sequence[str], None] = '10c7115345f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type
    user_role = sa.Enum('client', 'umkm', 'admin', name='userrole')
    user_role.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=user_role,
               nullable=False,
               postgresql_using="role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('client', 'umkm', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###

    # Drop the enum type
    user_role = sa.Enum('client', 'umkm', 'admin', name='userrole')
    user_role.drop(op.get_bind(), checkfirst=True)
