"""add_user_id_in_foods_table

Revision ID: e9a1ab705be1
Revises: c7e6e0b8a34b
Create Date: 2025-12-06 01:03:58.571659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e9a1ab705be1'
down_revision: Union[str, Sequence[str], None] = 'c7e6e0b8a34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'foods', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_column('foods', 'user_id')
    # ### end Alembic commands ###
